### ISSUE TITLE
The Heck?

### ISSUE THREAD

**Issue by HockeyD8** [matkoniecz/AIAI#61] opened 2018-04-02 18:15 UTC
why AIAI? Just Why?
![what in the world](https://user-images.githubusercontent.com/34627054/38208832-4be90282-3680-11e8-83bd-107d3b543deb.PNG)

**Comment by HockeyD8** [comment] 2018-04-02 18:15
2 AIAIs were running at the same time, BTW

**Comment by matkoniecz** [comment] 2018-04-08 15:01
It is building separate drop and pickup for every route, it is much easier than building large station for multiple routes.

In this case it is not a bug, so I will close it.

**Closed as completed by matkoniecz** 2018-04-08 15:01 UTC

**Comment by HockeyD8** [comment] 2018-04-12 21:32
Ah ok. Thanks.

**Comment by HockeyD8** [comment] 2019-05-04 18:03
Thomas Jacobs is a fan of Kongregate, and thinks you will love it too!
Kongregate has tens of thousands of free games that you can play anytime, right from your web browser. Complete online game achievements to win badges and points to level up, connect with other players in the community and show the world what you've got.
http://www.kongregate.com/?email=invitation&referrer=HockeyD8

Dolphin Olympics 2
http://www.kongregate.com/games/arawkins/dolphin-olympics-2?email=invitation&referrer=HockeyD8

Learn to Fly
http://www.kongregate.com/games/light_bringer777/learn-to-fly?email=invitation&referrer=HockeyD8

Super Stacker 2
http://www.kongregate.com/games/inXile_Ent/super-stacker-2?email=invitation&referrer=HockeyD8

Death vs Monstars
http://www.kongregate.com/games/GameReclaim/death-vs-monstars?email=invitation&referrer=HockeyD8

Vector Runner
http://www.kongregate.com/games/DigYourOwnGrave/vector-runner?email=invitation&referrer=HockeyD8

Personal Message:




  
  Visit http://www.kongregate.com/unsubscribe_email?email=reply%2B02105dee9103d3ba8c9de42a8afed7c3f752961bdfefe3e692cf0000000116e1f0dd92a169ce1282ca11%40reply.github.com&token=79789d49132113ed8793c6236cb2525323f8c19b to block emails from Kongregate for this address.

  Kongregate - 450 Sansome St, 12th Floor - San Francisco, CA 94111
